apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-webapp
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-webapp
  template:
    metadata:
      labels:
        app: bookstore-webapp
    spec:
      initContainers:
        - name: wait-for-keycloak
          image: curlimages/curl:7.78.0
          command: [ 'sh', '-c', 'until curl -s http://keycloak:9191 > /dev/null; do echo waiting for keycloak; sleep 2; done;' ]
      containers:
        - name: bookstore-webapp
          image: salgotraja/bookstore-webapp
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bookstore-webapp-config
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10