apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-webapp
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-webapp
  template:
    metadata:
      labels:
        app: bookstore-webapp
    spec:
      initContainers:
        - name: wait-for-keycloak
          image: curlimages/curl:7.78.0
          command: [ 'sh', '-c', 'until curl -s http://keycloak:9191 > /dev/null; do echo waiting for keycloak; sleep 2; done;' ]
      containers:
        - name: bookstore-webapp
          image: salgotraja/bookstore-webapp
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: BOOKSTORE_API_GATEWAY_URL
              value: http://api-gateway:8989
            - name: OAUTH2_SERVER_URL
              value: "http://keycloak:9191"
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://tempo.monitoring.svc.cluster.local:9411/api/v2/spans
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: "http://keycloak:9191/realms/bookstore"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10