POST http://localhost:8082/api/orders
Content-Type: application/json

{
  "customer" : {
    "name": "Jagdish",
    "email": "jagdish@gmail.com",
    "phone": "999999999"
  },
  "deliveryAddress" : {
    "addressLine1": "Mahagun",
    "addressLine2": "Housing",
    "city": "Noida",
    "state": "UP",
    "zipCode": "201309",
    "country": "India"
  },
  "items": [
    {
      "code": "P100",
      "name": "Product 1",
      "price": 34.0,
      "quantity": 1
    }
  ]
}