apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-overrides
  namespace: monitoring
data:
  overrides.yaml: |
    overrides:
      "fake":
        ingestion_rate_strategy: "global"
        ingestion_rate_mb: 50
        ingestion_burst_size_mb: 100