apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    [dashboards]
    default_home_dashboard_path = /etc/grafana/provisioning/dashboards/default.json