apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'monitoring-role'
        vault.hashicorp.com/agent-inject-secret-grafana: 'secret/monitoring/grafana'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-grafana: |
          {{- with secret "secret/monitoring/grafana" -}}
          GF_SECURITY_ADMIN_USER={{ .Data.data.admin }}
          GF_SECURITY_ADMIN_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: grafana
          image: grafana/grafana:10.4.2
          ports:
            - containerPort: 3000
          command:
            - "sh"
            - "-c"
            - |
              set -a
              . /vault/secrets/grafana
              set +a
              exec /run.sh
          env:
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          emptyDir: {}