apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /positions/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push
        batchwait: 1s
        batchsize: 51200  # 50KB
        backoff_config:
          min_period: 500ms
          max_period: 5m
          max_retries: 10

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+)(-[0-9a-f]{8,10})?
            action: replace
            target_label: controller
          - source_labels: ['__meta_kubernetes_namespace']
            action: replace
            target_label: namespace
          - source_labels: ['__meta_kubernetes_pod_name']
            action: replace
            target_label: pod
          - source_labels: ['__meta_kubernetes_pod_container_name']
            action: replace
            target_label: container
          - source_labels: ['__meta_kubernetes_pod_label_app']
            action: replace
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
            separator: /
            replacement: /var/log/pods/*$1/*.log