global:
  enabled: true

server:
  dev:
    enabled: true
    devRootToken: "root"
  service:
    type: NodePort
  postStart:
    - /bin/sh
    - -c
    - |
      sleep 10
      until vault status > /dev/null 2>&1; do
        echo "Waiting for Vault to become ready..."
        sleep 2
      done
      vault secrets enable -path=secret kv-v2 || true
      vault auth enable kubernetes || true

ui:
  enabled: true
  serviceType: NodePort

injector:
  enabled: true
