apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'bookstore-role'
        vault.hashicorp.com/agent-inject-secret-rabbitmq: 'secret/bookstore/rabbitmq'
        vault.hashicorp.com/agent-inject-template-rabbitmq: |
          {{ with secret "secret/bookstore/rabbitmq" }}
          RABBITMQ_DEFAULT_USER={{ .Data.data.username }}
          RABBITMQ_DEFAULT_PASS={{ .Data.data.password }}
          {{ end }}
        vault.hashicorp.com/agent-inject-command-rabbitmq: "source /vault/secrets/rabbitmq"
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12.11-management
          ports:
            - containerPort: 5672
            - containerPort: 15672