apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: bookstore
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: bookstore
type: Opaque
stringData:
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: bookstore
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin1234"