apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: salgotraja/bookstore-catalog-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: DB_URL
              value: jdbc:postgresql://catalog-db:5432/postgres
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: SPRING_FLYWAY_REPAIR_ON_MIGRATION_ERROR
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: LOGGING_LEVEL_ROOT
              value: "DEBUG"
            - name: SWAGGER_API_GATEWAY_URL
              value: http://api-gateway:8989/catalog
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://tempo.monitoring.svc.cluster.local:9411/api/v2/spans
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10