apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'app-role'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-database: 'secret/bookstore/database'
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/bookstore/database" -}}
          export DB_USERNAME="{{ .Data.data.username }}"
          export DB_PASSWORD="{{ .Data.data.password }}"
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: catalog-service
          image: salgotraja/bookstore-catalog-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: DB_URL
              value: jdbc:postgresql://catalog-db:5432/postgres
            - name: SPRING_FLYWAY_REPAIR_ON_MIGRATION_ERROR
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: LOGGING_LEVEL_ROOT
              value: "DEBUG"
            - name: SWAGGER_API_GATEWAY_URL
              value: http://api-gateway:8989/catalog
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://tempo.monitoring.svc.cluster.local:9411
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10