apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin:

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks