apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.4.1
          args:
            - "-config.file=/etc/tempo-config.yml"
          ports:
            - containerPort: 3200
            - containerPort: 9411
          volumeMounts:
            - name: config
              mountPath: /etc/tempo-config.yml
              subPath: tempo.yml
      volumes:
        - name: config
          configMap:
            name: tempo-config