apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-db
  namespace: bookstore
spec:
  serviceName: "orders-db"
  replicas: 1
  selector:
    matchLabels:
      app: orders-db
  template:
    metadata:
      labels:
        app: orders-db
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'bookstore-role'
        vault.hashicorp.com/agent-inject-secret-database: 'secret/bookstore/database'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/bookstore/database" -}}
          POSTGRES_USER={{ .Data.data.username }}
          POSTGRES_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: "ordersdb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          command:
            - "sh"
            - "-c"
            - |
              set -a
              . /vault/secrets/database
              set +a
              exec docker-entrypoint.sh postgres
  volumeClaimTemplates:
    - metadata:
        name: postgresdb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi