
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: bookstore
spec:
  selector:
    app: orders-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: bookstore
spec:
  selector:
    app: catalog-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-db
  namespace: bookstore
spec:
  selector:
    app: notifications-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432