apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'app-role'
        vault.hashicorp.com/agent-inject-secret-keycloak: 'secret/bookstore/keycloak'
        vault.hashicorp.com/agent-inject-template-keycloak: |
          {{- with secret "secret/bookstore/keycloak" -}}
          KEYCLOAK_ADMIN="{{ .Data.data.admin }}"
          KEYCLOAK_ADMIN_PASSWORD="{{ .Data.data.password }}"
          {{- end }}
        vault.hashicorp.com/template-static-secret-render-interval: "30"
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          command:
            - "sh"
            - "-c"
            - |
              export $(cat /vault/secrets/keycloak | xargs)
              echo "Starting Keycloak with admin: $KEYCLOAK_ADMIN"
              /opt/keycloak/bin/kc.sh start-dev --import-realm --http-port=9191
          ports:
            - containerPort: 9191
          env:
            - name: KC_HTTP_PORT
              value: "9191"
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config