apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          args: ["start-dev", "--import-realm", "--http-port=9191"]
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
          ports:
            - containerPort: 9191
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HTTP_PORT
              value: "9191"
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config