apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: bookstore
spec:
  type: NodePort
  ports:
    - port: 9191
      targetPort: 9191
      protocol: TCP
      name: http
  selector:
    app: keycloak