apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-policy
  namespace: bookstore
data:
  policy.hcl: |
    path "secret/data/bookstore/*" {
      capabilities = ["read", "list"]
    }
    path "secret/metadata/bookstore/*" {
      capabilities = ["read", "list"]
    }