apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'catalog-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['catalog-service.bookstore.svc.cluster.local:8081']

      - job_name: 'order-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['order-service.bookstore.svc.cluster.local:8082']

      - job_name: 'notification-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['notification-service.bookstore.svc.cluster.local:8083']

      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['api-gateway.bookstore.svc.cluster.local:8989']

      - job_name: 'bookstore-webapp'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['bookstore-webapp.bookstore.svc.cluster.local:8080']