apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: bookstore
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: bookstore.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookstore-webapp
                port:
                  number: 8080